# Generated by Django 4.2.7 on 2025-07-27 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespachoAduanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.CharField(max_length=50, unique=True, verbose_name='Número de Referencia Interno')),
                ('tipo_declaracion', models.CharField(choices=[('IM4', 'Importación para el Consumo'), ('EX1', 'Exportación Definitiva'), ('IM5', 'Admisión Temporal'), ('EX3', 'Reexportación'), ('IT1', 'Importación Temporal'), ('ET1', 'Exportación Temporal')], max_length=3)),
                ('descripcion_mercancia', models.TextField(verbose_name='Descripción Comercial')),
                ('partida_arancelaria', models.CharField(max_length=10)),
                ('pais_origen', models.CharField(max_length=2)),
                ('pais_procedencia', models.CharField(max_length=2)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=10)),
                ('peso_bruto', models.DecimalField(decimal_places=3, max_digits=12)),
                ('peso_neto', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_fob', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_cif', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, max_digits=8)),
                ('aduana_registro', models.CharField(max_length=50)),
                ('numero_manifiesto', models.CharField(blank=True, max_length=50)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador - En preparación'), ('ELABORADO', 'Elaborado - Listo para enviar'), ('ENVIADO', 'Enviado - Transmitido a SIDUNEA'), ('OBSERVADO', 'Observado - Con observaciones'), ('PAGADO', 'Pagado - Tributos cancelados'), ('NUMERADO', 'Numerado - DIM/DUI asignado'), ('EN_AFORO', 'En Aforo - Revisión física/documental'), ('LEVANTE', 'Levante - Autorizado para retiro'), ('CONCLUIDO', 'Concluido - Mercancía retirada'), ('ARCHIVADO', 'Archivado - Proceso finalizado')], default='BORRADOR', max_length=20)),
                ('numero_dim', models.CharField(blank=True, max_length=50, verbose_name='Número DIM/DUI')),
                ('canal_asignado', models.CharField(blank=True, choices=[('VERDE', 'Canal Verde - Levante automático'), ('AMARILLO', 'Canal Amarillo - Revisión documental'), ('ROJO', 'Canal Rojo - Revisión física')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despacho Aduanero',
                'verbose_name_plural': 'Despachos Aduaneros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionAduanera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravamen_aduanero', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ice', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iehd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tributos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('numero_comprobante_pago', models.CharField(blank=True, max_length=50)),
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='customs.despachoaduanero')),
            ],
            options={
                'verbose_name': 'Liquidación Aduanera',
                'verbose_name_plural': 'Liquidaciones Aduaneras',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura Comercial'), ('BL', 'Bill of Lading'), ('GUIA_AEREA', 'Guía Aérea'), ('CRT', 'Carta de Porte'), ('PACKING', 'Lista de Empaque'), ('DAV', 'Declaración Andina de Valor'), ('POLIZA', 'Póliza de Seguro'), ('CERT_ORIGEN', 'Certificado de Origen'), ('SENASAG', 'Certificado SENASAG'), ('OTRO', 'Otro Documento')], max_length=20)),
                ('numero_documento', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='despachos/documentos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='customs.despachoaduanero')),
            ],
            options={
                'verbose_name': 'Documento del Despacho',
                'verbose_name_plural': 'Documentos del Despacho',
                'ordering': ['tipo_documento', 'fecha_emision'],
                'unique_together': {('despacho', 'tipo_documento', 'numero_documento')},
            },
        ),
    ]
