# Generated by Django 4.2.7 on 2025-07-27 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('direccion_legal', models.TextField()),
                ('ciudad', models.CharField(default='Santa Cruz', max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('representante_legal', models.CharField(max_length=100)),
                ('ci_representante', models.CharField(max_length=20)),
                ('tipo_operador', models.CharField(choices=[('IMP', 'Importador'), ('EXP', 'Exportador'), ('BOTH', 'Importador/Exportador')], default='IMP', max_length=4)),
                ('tipo_cliente', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('NUEVO', 'Nuevo')], default='REGULAR', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('volumen_operaciones', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('calificacion', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20)),
                ('puntaje', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('evaluado_por', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'Evaluación del Cliente',
                'verbose_name_plural': 'Evaluaciones del Cliente',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('es_principal', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'Contacto del Cliente',
                'verbose_name_plural': 'Contactos del Cliente',
            },
        ),
    ]
