# Generated by Django 4.2.7 on 2025-07-27 14:40

import apps.documents.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=apps.documents.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('tamaño_archivo', models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('hash_archivo', models.CharField(blank=True, help_text='Hash SHA-256 del archivo', max_length=64, null=True)),
                ('fecha_documento', models.DateField(help_text='Fecha del documento original')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('emisor', models.CharField(help_text='Quien emitió el documento', max_length=200)),
                ('numero_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('validado', 'Validado'), ('observado', 'Observado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='pendiente', max_length=15)),
                ('medio', models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital'), ('ambos', 'Físico y Digital')], default='digital', max_length=10)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('validado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_validacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clients.cliente')),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_generales', to='customs.despachoaduanero')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos_documento',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('comercial', 'Comercial'), ('transporte', 'Transporte'), ('origen', 'Origen'), ('sanitario', 'Sanitario'), ('legal', 'Legal'), ('financiero', 'Financiero'), ('otros', 'Otros')], max_length=15)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'documentos_tipo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('validacion', 'Validación'), ('observacion', 'Observación'), ('archivo', 'Archivo')], max_length=15)),
                ('usuario', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('destinatario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_devolucion_esperada', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='documents.documento')),
            ],
            options={
                'verbose_name': 'Registro Documento',
                'verbose_name_plural': 'Registros Documento',
                'db_table': 'documentos_registro',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='ListaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_documentos_recibidos', models.IntegerField(default=0)),
                ('total_documentos_validados', models.IntegerField(default=0)),
                ('total_documentos_observados', models.IntegerField(default=0)),
                ('total_documentos_archivados', models.IntegerField(default=0)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista Maestra',
                'verbose_name_plural': 'Listas Maestras',
                'db_table': 'documentos_lista_maestra',
                'ordering': ['-año', '-mes'],
                'unique_together': {('año', 'mes')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.tipodocumento'),
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('archivo', models.FileField(upload_to=apps.documents.models.documento_upload_path)),
                ('descripcion_cambios', models.TextField(blank=True, null=True)),
                ('fecha_version', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.CharField(max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documents.documento')),
            ],
            options={
                'verbose_name': 'Versión Documento',
                'verbose_name_plural': 'Versiones Documento',
                'db_table': 'documentos_version',
                'ordering': ['-version'],
                'unique_together': {('documento', 'version')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('numero_documento', 'tipo_documento', 'cliente')},
        ),
    ]
